# Generated by Django 5.2.8 on 2025-12-06 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Content', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('PublishedDate', models.DateTimeField(blank=True, null=True)),
                ('IsDraft', models.BooleanField(default=True)),
                ('Category', models.CharField(blank=True, choices=[('technology', 'Technology'), ('programming', 'Programming'), ('ai_ml', 'AI & Machine Learning'), ('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('cyber_security', 'Cyber Security'), ('cloud_computing', 'Cloud Computing'), ('data_science', 'Data Science'), ('business', 'Business'), ('startup', 'Startups'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('education', 'Education'), ('health', 'Health & Fitness'), ('lifestyle', 'Lifestyle'), ('travel', 'Travel'), ('food', 'Food & Recipes'), ('gaming', 'Gaming'), ('entertainment', 'Entertainment'), ('science', 'Science'), ('productivity', 'Productivity'), ('design', 'UI/UX & Design'), ('photography', 'Photography'), ('news', 'News'), ('reviews', 'Reviews & Opinions')], max_length=255, null=True)),
                ('FeatureImage', models.ImageField(blank=True, null=True, upload_to='blogs_img')),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-PublishedDate'],
            },
        ),
    ]
