# Generated by Django 5.2.8 on 2025-12-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_categories_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='CategoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='category_img'),
        ),
    ]
