# Generated by Django 5.2.8 on 2025-12-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_categories_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='CategoryDescription',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
